crowdin/src/Entity/LangHasUser.php
<?php

namespace App\Entity;

use App\Repository\LangHasUserRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=LangHasUserRepository::class)
 */
class LangHasUser
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=5)
     */
    private $lang_code;

    /**
     * @ORM\Column(type="integer")
     */
    private $user_id;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLangCode(): ?string
    {
        return $this->lang_code;
    }

    public function setLangCode(string $lang_code): self
    {
        $this->lang_code = $lang_code;

        return $this;
    }

    public function getUserId(): ?int
    {
        return $this->user_id;
    }

    public function setUserId(int $user_id): self
    {
        $this->user_id = $user_id;

        return $this;
    }
}

crowdin/src/Form/LangHasUserType.php
<?php

namespace App\Form;

use App\Entity\Lang;
use App\Entity\LangHasUser;
use Doctrine\ORM\EntityRepository;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class LangHasUserType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $choice_lang = $options['data'];
        $builder
            ->add('lang_code', ChoiceType::class,
                [
                    'label'=>'Quelle langue maitrisez vous?',
                    'choices' => $choice_lang,
                    'choice_value' => function ($row) {
                        return $row;
                    },
                    'data_class'=>null
                ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
        'data_class' => null,
        ]);
    }
}

crowdin/src/Controller/LangHasUserController.php
<?php

namespace App\Controller;

use App\Entity\Lang;
use App\Entity\User;
use App\Entity\LangHasUser;
use App\Form\LangHasUserType;
use App\Repository\LangHasUserRepository;
use App\Repository\LangRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Knp\Component\Pager\PaginatorInterface;
use Doctrine\Persistence\ManagerRegistry;

/**
 * @Route("/lang/has/user")
 */
class LangHasUserController extends AbstractController
{
    /**
     * @Route("/", name="app_lang_has_user_index", methods={"GET"})
     */
    public function index(ManagerRegistry $doctrine, Request $request, PaginatorInterface $paginator): Response
    {
        $user = $this->getUser();
        $langhasuser = $this->getDoctrine()->getRepository(LangHasUser::class)->
        findBy(['user_id' => $user->getId()]);

        $langhasuser = $paginator->paginate(
            $langhasuser, // Requête contenant les données à paginer (ici nos articles)
            $request->query->getInt('page', 1), // Numéro de la page en cours, passé dans l'URL, 1 si aucune page
            6 // Nombre de résultats par page
        );

        return $this->render('lang_has_user/index.html.twig', [
            'lang_has_users' => $langhasuser,
        ]);
    }

    /**
     * @Route("/new", name="app_lang_has_user_new", methods={"GET", "POST"})
     */
    public function new(ManagerRegistry $doctrine, Request $request, LangHasUserRepository $langHasUserRepository, EntityManagerInterface $em): Response
    {
        $user = $this->getUser();
        $langHasUser = new LangHasUser();
        $choice_langs = $doctrine->getRepository(Lang::class)->createOptionSelect($doctrine, $em);
        $form = $this->createForm(LangHasUserType::class,$langHasUser, ['data'=>$choice_langs]);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $langHasUser->setUserId($user->getId());
            $langHasUser->setLangCode($form->get("lang_code")->getData());

            $condition = $this->getDoctrine()->getRepository(LangHasUser::class)->
            findBy(['lang_code' => $form->get("lang_code")->getData(), 'user_id' => $user->getId()]);

            if (!$condition) {
                $langHasUserRepository->add($langHasUser);
            }

            return $this->redirectToRoute('app_lang_has_user_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('lang_has_user/new.html.twig', [
            'lang_has_user' => $langHasUser,
            'form' => $form->createView(),
        ]);
    }
    /**
     * @Route("/{id}/edit", name="app_lang_has_user_edit", methods={"GET", "POST"})
     */
    public function edit(ManagerRegistry $doctrine, Request $request, LangHasUser $langHasUser, LangHasUserRepository $langHasUserRepository, EntityManagerInterface $em, $id): Response
    {
        $langHasUser = $em->getRepository(LangHasUser::class)->find($id);
        $user = $this->getUser();
        $choice_langs = $doctrine->getRepository(Lang::class)->createOptionSelect($doctrine, $em);
        $form = $this->createForm(LangHasUserType::class, $langHasUser, ['data'=>$choice_langs]);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $langHasUser->setLangCode($form->get("lang_code")->getData());
            $condition = $this->getDoctrine()->getRepository(LangHasUser::class)->
            findBy(['lang_code' => $form->get("lang_code")->getData(), 'user_id' => $user->getId()]);
            
            if (!$condition) {
                $langHasUserRepository->add($langHasUser);
            }
            return $this->redirectToRoute('app_lang_has_user_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('lang_has_user/edit.html.twig', [
            'lang_has_user' => $langHasUser,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="app_lang_has_user_delete", methods={"POST"})
     */
    public function delete(Request $request, LangHasUser $langHasUser, LangHasUserRepository $langHasUserRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$langHasUser->getId(), $request->request->get('_token'))) {
            $langHasUserRepository->remove($langHasUser);
        }

        return $this->redirectToRoute('app_lang_has_user_index', [], Response::HTTP_SEE_OTHER);
    }
}

crowdin/templates/lang_has_user/_delete_form.html.twig
<form method="post" action="{{ path('app_lang_has_user_delete', {'id': lang_has_user.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ lang_has_user.id) }}">
    <button class="btn">Delete</button>
</form>

crowdin/templates/lang_has_user/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

crowdin/templates/lang_has_user/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit LangHasUser{% endblock %}

{% block body %}
    <h1>Edit LangHasUser</h1>

    {{ include('lang_has_user/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_lang_has_user_index') }}">back to list</a><br>
    <a href="{{ path('app_user_index') }}">back to user</a>

    {{ include('lang_has_user/_delete_form.html.twig') }}
{% endblock %}

crowdin/templates/lang_has_user/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}LangHasUser index{% endblock %}

{% block body %}
    <h1>LangHasUser index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Lang_code</th>
                <th>User_id</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for lang_has_user in lang_has_users %}
            <tr>
                <td>{{ lang_has_user.id }}</td>
                <td>{{ lang_has_user.langCode }}</td>
                <td>{{ lang_has_user.userId }}</td>
                <td>

                    <a href="{{ path('app_lang_has_user_edit', {'id': lang_has_user.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_lang_has_user_new') }}">Create new</a><br>
    <a href="{{ path('app_user_index') }}">back to user</a>
{% endblock %}

crowdin/templates/lang_has_user/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New LangHasUser{% endblock %}

{% block body %}
    <h1>Create new LangHasUser</h1>

    {{ include('lang_has_user/_form.html.twig') }}

    <a href="{{ path('app_lang_has_user_index') }}">back to list</a>
{% endblock %}

crowdin/templates/lang_has_user/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}LangHasUser{% endblock %}

{% block body %}
    <h1>LangHasUser</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ lang_has_user.id }}</td>
            </tr>
            <tr>
                <th>Lang_code</th>
                <td>{{ lang_has_user.langCode }}</td>
            </tr>
            <tr>
                <th>User_id</th>
                <td>{{ lang_has_user.userId }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_lang_has_user_index') }}">back to list</a>

    <a href="{{ path('app_lang_has_user_edit', {'id': lang_has_user.id}) }}">edit</a>

    {{ include('lang_has_user/_delete_form.html.twig') }}
{% endblock %}